### ISSUE TITLE
"Computed" state?

### ISSUE THREAD

**Issue by davidhewitt** [csharad/ruukh#18]
This crate is awesome, nice one!

One thing I really love about Vue.js is the "computed" and "watch" APIs, for reacting to state changes. Do you have a feeling whether Ruukh could support something like this? It looks to me at the moment Ruukh uses dirty checking, would presumably have to use some kind of Observable pattern instead...

If it's something you're not hugely interested in but might be prepared to play with, I would happily try this out in a fork and see what you think 😄

**Comment by csharad** [comment]
Thanks. Vue uses observables which is what I tried to use initially and failed from the ergonomics viewpoint. In JS, Vue uses some magic to modify the object into a reactive one. But here in Rust, we need to be explicit about the type. To create an observable we would need to wrap up the state like `Observable<T>` which introduces overhead while use. So I went the way of React here but introduced automatic state checking mechanism to behave like Vue. In a way this framework takes what's best for it from both of these frameworks not just tying itself to one.
After saying all that, If you are interested to experiment with it and are willing to provide an ergonomic path to use such a state, then why not (we are still at the stage of experimentation still).

With regards to computed state, currently you can use a method instead.
```rust
#[state]
count: i32

fn double_count(&self) -> i32 {
  self.count * 2
}
``` 
With regards to watch, you may use `updated` method on `Lifecycle` trait (currently only props are supported). 
```rust
impl Lifecycle for MyApp {
  fn updated(&self, old_props: Self::Props) {
    // Do something on props changes.
  }
}
```

**Comment by davidhewitt** [comment]
Thanks, yeah I think preserving ergonomics is very important. I've had some ideas that your #[component] attribute might fit nicely with.

Have you got any benchmarking setup? I suspect this is one of those things where it'll be hard to know the overhead of state comparison vs observables without measurement :)

**Comment by csharad** [comment]
No, currently we don't have any benchmarking setup. I am focused in making it feature complete first. Performance optimizations come later.

**Comment by csharad** [comment]
Closing this issue as `computed` and `watch` like abilities are already achievable.
