### ISSUE TITLE
error[E0446]: private type `app::DeitiesState` in public interface  

### ISSUE THREAD

**Issue by zengsai** [csharad/ruukh#23]
error[E0446]: private type `app::DeitiesState` in public interface
 --> src/app.rs:7:1
  |
7 | #[component]
  | -^^^^^^^^^^^
  | |
  | can't leak private type
  | `app::DeitiesState` declared as private

error[E0446]: private type `app::DeitiesStatus` in public interface

my app layout is:

![image](https://user-images.githubusercontent.com/163317/46900385-ddd5d580-ced3-11e8-8b61-df290867ceb7.png)

**Comment by csharad** [comment]
Issue resolved.
